version: "3.9"
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.8.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.8.0
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.8.0
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch
      - descriptions_interface

  filebeat:
    build:
      context: filebeat/
    volumes:
      - type: volume
        source: pptester_shared
        target: /usr/share/pptester
        read_only: true

  descriptions_interface:
    build:
      context: ./descriptions/
      dockerfile: Dockerfile
    environment:
      - MARIADB_DATABASE_NAME=service_descriptions_db
      - MARIADB_DATABASE_USERNAME=firefly
      - MARIADB_DATABASE_PASSWORD=firefly_developer_1234
      - MARIADB_DATABASE_HOST_ADDRESS=descriptions_database
      - MARIADB_DATABASE_HOST_PORT=3306
      - PPTESTER_DATABATE_REMOTE=True
      - PPTESTER_LOG_FILE=/usr/share/pptester/output.log
      - FLASK_APP=/app/source/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    working_dir: /app/source
    command: "python -m flask run --no-reload --no-debugger --host=0.0.0.0 --port=7777"
    volumes:
      - type: volume
        source: pptester_shared
        target: /usr/share/pptester
    ports:
      - "7777:7777"
    expose:
      - 7777
    depends_on:
      - descriptions_database

  descriptions_database:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_SKIP_TEST_DB=yes
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root_developer_1234
      - MARIADB_USER=firefly
      - MARIADB_PASSWORD=firefly_developer_1234
      - MARIADB_DATABASE=service_descriptions_db
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - /images_persistent/mariadb:/bitnami/mariadb
      - data:/bitnami/mariadb/data


  mock_service:
    build:
      context: ./mock/
      dockerfile: Dockerfile
    working_dir: /app/source
    command: "python -m flask run --no-reload --no-debugger --host=0.0.0.0 --port=6500"
    environment:
      - FLASK_APP=/app/app.py
    ports:
      - "6500:6500"
    expose:
      - 6500
    depends_on:
      - descriptions_database


volumes:
  data:
    driver: local
  elasticsearch:
    driver: local
  pptester_shared:
    driver: local