filebeat.processors:
- drop_fields:
  fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.type", "agent.version", "ecs.version", "input.type", "log.offset", "version"]

filebeat.inputs:
- type: log
  paths:
    - /usr/share/pptester/output.log

output.logstash:
  hosts: ["logstash:5044"]
